name: GridSearchVisualiser
version: 1.0.0
description: Visualise and explain pathfinding on grids.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  over_react: '>=2.0.0 <3.0.0'
  optional: '^3.0.0+2'
  tuple: '^1.0.2'
  vector_math: '^2.0.8'
  js: '^0.6.1'

dev_dependencies:
  build_runner: '^1.1.2'
  build_web_compilers: '^1.0.0'

transformers:
- over_react