name: Test, Build, Deploy and Release
on: 
  push
env:
  refs/heads/master_branch: master
  refs/heads/master_release: true
  refs/heads/master_release-prerelease: false
  refs/heads/master_deploy: true
  refs/heads/master_deploy-folder: 'test'
  refs/heads/master_deploy-clean-exclude: '["stable", "development"]'
  
  refs/heads/stable_branch: stable
  refs/heads/stable_release: true
  refs/heads/stable_release-prerelease: true
  refs/heads/stable_deploy: true
  refs/heads/stable_deploy-folder: stable
  refs/heads/stable_deploy-clean-exclude: '["master", "development"]'
  
  refs/heads/develop_branch: develop
  refs/heads/develop_release: false
  refs/heads/develop_deploy: true
  refs/heads/develop_deploy-folder: 'develop'
  refs/heads/develop_deploy-clean-exclude: '["master", "stable"]'

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Install dependencies
      working-directory: jps_visualiser
      run: pub get && pub global activate webdev
      
    #- name: Run tests
    #  working-directory: jps_visualiser
    #  run: pub run test
      
    - name: Run build
      working-directory: jps_visualiser
      run: pub global run webdev build --output build

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: jps_visualiser/build
  
  deploy:
    needs: [test_and_build]
    if: success() && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/stable' || github.ref == 'refs/heads/develop')
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Download
        uses: actions/download-artifact@v1
        with:
          name: build
        
      - run: echo $FOLDER && echo $TEST && mkdir -p deploy/$FOLDER/ && mv build/web/ deploy/$FOLDER/
        env:
          FOLDER: ${{ join('test-', env[join(github.ref, '_deploy-folder')]) }}
          TEST: ${{ github.ref }}
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy
  
  release:
    needs: [deploy]
    if: success() && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/stable')
    runs-on: ubuntu-latest
    
    steps:
      - name: Download
        uses: actions/download-artifact@v1
        with:
          name: build
          
      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env[join(github.ref, '_branch')] }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: ${{ env[join(github.ref, '_release-prerelease')] }}
